
configuration:
  jupyterhub:

    profiles:
      user: 
        - displayName: "Jupyter EDS Base Notebook - DEV"
          slug: "eds-base-dev"
          image: "aphp/jupyterlab:eds-base-notebook_ubuntu-22.04-dev"
          imagePullPolicy: "Always"
        - displayName: "Jupyter EDS OCAML Notebook - DEV"
          slug: "eds-ocaml-dev"
          image: "aphp/jupyterlab:eds-ocaml-notebook_ubuntu-22.04-dev"
          imagePullPolicy: "Always"
        - displayName: "Jupyter Minimal Notebook"
          slug: "minimal"
          image: "quay.io/jupyter/minimal-notebook:latest"
          imagePullPolicy: "Always"
        - displayName: "Jupyter Datascience Notebook"
          slug: "datascience"
          image: "quay.io/jupyter/datascience-notebook:latest"
          imagePullPolicy: "Always"

      collaboration:

        - displayName: "Jupyter EDS Base Notebook - DEV"
          slug: "eds-base-dev"
          image: "aphp/jupyterlab:eds-base-notebook_ubuntu-22.04-dev"
          imagePullPolicy: "Always"
        - displayName: "Jupyter EDS OCAML Notebook - DEV"
          slug: "eds-ocaml-dev"
          image: "aphp/jupyterlab:eds-ocaml-notebook_ubuntu-22.04-dev"
          imagePullPolicy: "Always"

persistence:
  createPVC:
  - name: data-hdd-pvc
    storageClassName: "standard"
    accessMode: "ReadWriteOnce"
    size: "5Gi"
  - name: data-ssd-pvc 
    storageClassName: "standard"
    accessMode: "ReadWriteOnce"
    size: "5Gi"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

jupyterhub:
  enabled: true
  debug:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/app-root: "/jupyter"
    hosts:
    - "localhost"
    tls: []

  hub:
    image:
      pullPolicy: "Always"
    baseUrl: "/jupyter"
    db:
      type: "sqlite-pvc"
      upgrade:
      pvc:
        annotations: {}
        selector: {}
        accessModes:
          - "ReadWriteOnce"
        storage: "2Gi"
        storageClassName: "standard"

    config:
      Authenticator:
        admin_users:
          - "admin1" 
          - "admin2"
        allowed_users:
          - "helix-local"
          - "user1"
          - "user2"

      DummyAuthenticator:
        password: "supersecretpassword"
      JupyterHub:
        authenticator_class: "dummy"

    extraEnv:
      PROJECT: "helix-local"
      JHUB_DEFAULT_URL: "/jupyter/hub/spawn/helix-local"

    redirectToServer: false

    extraVolumeMounts:
      - name: "extra-config"
        mountPath: "/usr/local/etc/jupyterhub/jupyterhub_config.d"

    extraVolumes:
      - name: "extra-config"
        configMap:
          name: "jupyterhub-extra-config"

      
  scheduling:
    userScheduler:
      enabled: false
    podPriority:
      enabled: false
    userPlaceholder:
      enabled: false

  proxy:
    service:
      type: "ClusterIP"

  prePuller:
    continuous:
      enabled: false
    hook:
      enabled: false

  cull:
    enabled: true
    timeout: 3600
    every: 300

  singleuser:
    podNameTemplate: "jupyter-{unescaped_username}"

    extraEnv:
      PYDEVD_DISABLE_FILE_VALIDATION: "1"

    storage:
      dynamic:
        storageClass: "standard"
        storageAccessModes:
        - "ReadWriteOnce"
      capacity: "5Gi"

      extraVolumeMounts:
      - name: "helix-data-hdd"
        mountPath: "/data/hdd"
      - name: "helix-data-ssd"
        mountPath: "/data/ssd"

      extraVolumes:
      - name: "helix-data-hdd"
        persistentVolumeClaim:
          claimName: "data-hdd-pvc"
      - name: "helix-data-ssd"
        persistentVolumeClaim:
          claimName: "data-ssd-pvc"
        

    lifecycleHooks:
      postStart:
        exec:
          command:
          - "sh"
          - "-c"
          - "if [ -d /tmp/home ]; then cp -rf /tmp/home/.[^.]* /home/jovyan/; fi"

    cpu:
      limit: 2
      guarantee: 0.5
    memory:
      limit: "8G"
      guarantee: "4G"