name: helix-helmchart-ci
run-name: HELIX Helm Chart CI triggered by @${{ github.actor }}

on:
 push:

jobs:
  aphp-chart-ci-workflow:
    uses: "aphp/ci-workflows/.github/workflows/chart-ci.yml@polaris_update"
    with:
      kubernetes-version: "1.24.2"
      chart-dir: "charts/helix"
      chart-values: "./charts/helix/values.yaml"
